version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: laravel:master    # Required. Must be in the same fork network.
    mergeMethod: rebase  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees:              # Optional
      - spam-n-eggs
    reviewers:              # Optional
      - spam-n-eggs
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - spam-n-eggs
label: ":arrow_heading_down: pull"  # Optional
